#include <iostream>
#include <cmath>
#include <math.h>

using namespace std;


class Myexception
{

};

void fo(float value) {

	if (value <= 0) {
		throw exception("Число должно быть больше 0!");
	}

	if (cin >> value) {
		throw exception("Введите число!");
	}
	cout << "Переменная " << value << endl;
}


int main() {
    setlocale(LC_ALL, "RU");

	float a;
    cout << "enter nomber" << endl;
	cin >> a;

	try
	{
		fo(a);
	}
	catch (const exception &ex)
	{
		cout << ex.what() << endl;
	}
    

}


// https://www.youtube.com/watch?v=wCUl7yTHWq8